<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<AllowUnsafeBlocks>False</AllowUnsafeBlocks>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
		<InformationalVersion>1.0.0</InformationalVersion>
		<Company>MalkanTeknoloji</Company>
		<Product>Telemetry</Product>
		<Title>Telemetry SCADA Sistemi</Title>
		<Copyright>Copyright © 2025</Copyright>
		<AssemblyName>$(MSBuildProjectName)</AssemblyName>
		<AppDesignerFolder>Properties</AppDesignerFolder>
	</PropertyGroup>

	<PropertyGroup Label="Avalonia">
		<AvaloniaNameGeneratorIsEnabled>False</AvaloniaNameGeneratorIsEnabled>
		<AvaloniaNameGeneratorAttachDevTools>False</AvaloniaNameGeneratorAttachDevTools>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<ApplicationIcon>Resources\yilmak2 - Kopya - Kopya.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Img\**" />
	  <Compile Remove="publish_api_fix\**" />
	  <Compile Remove="publish_webapp\**" />
	  <Compile Remove="TekstilScada.Core\**" />
	  <Compile Remove="TekstilScada.WebAPI\**" />
	  <Compile Remove="TekstilScada.WebApp\**" />
	  <Compile Remove="TelemetryScada.Core\**" />
	  <Compile Remove="TelemetryScada.WebAPI\**" />
	  <Compile Remove="TelemetryScada.WebApp\**" />
	  <Compile Remove="Telemetry.Core\**" />
	  <Compile Remove="Telemetry.WebAPI\**" />
	  <Compile Remove="Telemetry.WebApp\**" />
	  <Compile Remove="TelemetryTelemetry.Core\**" />
	  <Compile Remove="TelemetryTelemetry.WebAPI\**" />
	  <Compile Remove="TelemetryTelemetry.WebApp\**" />
	  <Compile Remove="Telemetry.Api\**" />
	  <Compile Remove="Telemetry.Core1\**" />
	  <Compile Remove="Telemetry.Core\**" />
	  <Compile Remove="Telemetry.WebAPI1\**" />
	  <Compile Remove="Telemetry.WebAPI\**" />
	  <Compile Remove="Telemetry.WebApp1\**" />
	  <Compile Remove="Telemetry.WebApp\**" />
	  <Compile Remove="Telemetry.Web\**" />
	  <Compile Remove="Universalscada.Core\**" />
	  <Compile Remove="Universalscada.Module.Textile\**" />
	  <Compile Remove="Universalscada.WebAPI\**" />
	  <Compile Remove="Universalscada.WebApp\**" />
	  <Compile Remove="yilmak_scada_setup\**" />
	  <EmbeddedResource Remove="Img\**" />
	  <EmbeddedResource Remove="publish_api_fix\**" />
	  <EmbeddedResource Remove="publish_webapp\**" />
	  <EmbeddedResource Remove="TekstilScada.Core\**" />
	  <EmbeddedResource Remove="TekstilScada.WebAPI\**" />
	  <EmbeddedResource Remove="TekstilScada.WebApp\**" />
	  <EmbeddedResource Remove="TelemetryScada.Core\**" />
	  <EmbeddedResource Remove="TelemetryScada.WebAPI\**" />
	  <EmbeddedResource Remove="TelemetryScada.WebApp\**" />
	  <EmbeddedResource Remove="Telemetry.Core\**" />
	  <EmbeddedResource Remove="Telemetry.WebAPI\**" />
	  <EmbeddedResource Remove="Telemetry.WebApp\**" />
	  <EmbeddedResource Remove="TelemetryTelemetry.Core\**" />
	  <EmbeddedResource Remove="TelemetryTelemetry.WebAPI\**" />
	  <EmbeddedResource Remove="TelemetryTelemetry.WebApp\**" />
	  <EmbeddedResource Remove="Telemetry.Api\**" />
	  <EmbeddedResource Remove="Telemetry.Core1\**" />
	  <EmbeddedResource Remove="Telemetry.Core\**" />
	  <EmbeddedResource Remove="Telemetry.WebAPI1\**" />
	  <EmbeddedResource Remove="Telemetry.WebAPI\**" />
	  <EmbeddedResource Remove="Telemetry.WebApp1\**" />
	  <EmbeddedResource Remove="Telemetry.WebApp\**" />
	  <EmbeddedResource Remove="Telemetry.Web\**" />
	  <EmbeddedResource Remove="Universalscada.Core\**" />
	  <EmbeddedResource Remove="Universalscada.Module.Textile\**" />
	  <EmbeddedResource Remove="Universalscada.WebAPI\**" />
	  <EmbeddedResource Remove="Universalscada.WebApp\**" />
	  <EmbeddedResource Remove="yilmak_scada_setup\**" />
	  <None Remove="Img\**" />
	  <None Remove="publish_api_fix\**" />
	  <None Remove="publish_webapp\**" />
	  <None Remove="TekstilScada.Core\**" />
	  <None Remove="TekstilScada.WebAPI\**" />
	  <None Remove="TekstilScada.WebApp\**" />
	  <None Remove="TelemetryScada.Core\**" />
	  <None Remove="TelemetryScada.WebAPI\**" />
	  <None Remove="TelemetryScada.WebApp\**" />
	  <None Remove="Telemetry.Core\**" />
	  <None Remove="Telemetry.WebAPI\**" />
	  <None Remove="Telemetry.WebApp\**" />
	  <None Remove="TelemetryTelemetry.Core\**" />
	  <None Remove="TelemetryTelemetry.WebAPI\**" />
	  <None Remove="TelemetryTelemetry.WebApp\**" />
	  <None Remove="Telemetry.Api\**" />
	  <None Remove="Telemetry.Core1\**" />
	  <None Remove="Telemetry.Core\**" />
	  <None Remove="Telemetry.WebAPI1\**" />
	  <None Remove="Telemetry.WebAPI\**" />
	  <None Remove="Telemetry.WebApp1\**" />
	  <None Remove="Telemetry.WebApp\**" />
	  <None Remove="Telemetry.Web\**" />
	  <None Remove="Universalscada.Core\**" />
	  <None Remove="Universalscada.Module.Textile\**" />
	  <None Remove="Universalscada.WebAPI\**" />
	  <None Remove="Universalscada.WebApp\**" />
	  <None Remove="yilmak_scada_setup\**" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="appsettings.json" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="Resources\yilmak2 - Kopya - Kopya.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CircularProgressBar" Version="2.8.0.16" />
		<PackageReference Include="ClosedXML" Version="0.105.0" />
		<PackageReference Include="LiveCharts.WinForms" Version="0.9.7.1" />
		<PackageReference Include="LiveChartsCore.SkiaSharpView.WinForms" Version="2.0.2" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.22" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.7" />
		<PackageReference Include="MySql.Data" Version="9.4.0" />
		<PackageReference Include="ScottPlot" Version="5.0.55" />
		<PackageReference Include="ScottPlot.WinForms" Version="5.0.55" />
		<PackageReference Include="WinForms.DataVisualization" Version="1.10.0" />
		<PackageReference Include="WinSCP" Version="6.5.3" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="TekstilScada.Core\Telemetry.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="HslCommunication">
		  <HintPath>..\..\..\Downloads\HslCommunication\HslCommunication.dll</HintPath>
		</Reference>
		<Reference Include="VncSharpCore">
			<HintPath>..\..\..\Lib\VncSharpCore.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Localization1\Strings.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Strings.resx</DependentUpon>
	  </Compile>
	  <Compile Update="Properties\Resource1.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Resource1.resx</DependentUpon>
	  </Compile>
	  <Compile Update="Properties\Resources.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Resources.resx</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Localization1\Strings.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Strings.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Properties\Resource1.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>Resource1.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

</Project>