// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Universalscada.Core;

#nullable disable

namespace Universalscada.core.Migrations
{
    [DbContext(typeof(ScadaDbContext))]
    partial class ScadaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("Universalscada.Core.Meta.ProcessConstant", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Key");

                    b.ToTable("ProcessConstants");

                    b.HasData(
                        new
                        {
                            Key = "WATER_PER_LITER_SECONDS",
                            Description = "Su alma süresi katsayısı (saniye/litre).",
                            Value = 0.5
                        },
                        new
                        {
                            Key = "DRAIN_SECONDS",
                            Description = "Boşaltma işlemi için standart süre (saniye).",
                            Value = 120.0
                        });
                });

            modelBuilder.Entity("Universalscada.Core.Meta.StepParameterDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParameterKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StepTypeDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WordIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StepTypeDefinitionId");

                    b.ToTable("StepParameterDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataType = "short",
                            ParameterKey = "QUANTITY_LITERS",
                            StepTypeDefinitionId = 1,
                            Unit = "Litre",
                            WordIndex = 1
                        },
                        new
                        {
                            Id = 2,
                            DataType = "short",
                            ParameterKey = "TARGET_TEMP",
                            StepTypeDefinitionId = 2,
                            Unit = "°C",
                            WordIndex = 3
                        },
                        new
                        {
                            Id = 3,
                            DataType = "short",
                            ParameterKey = "DURATION_MINUTES",
                            StepTypeDefinitionId = 2,
                            Unit = "Dakika",
                            WordIndex = 4
                        },
                        new
                        {
                            Id = 4,
                            DataType = "short",
                            ParameterKey = "WORK_DURATION_MINUTES",
                            StepTypeDefinitionId = 3,
                            Unit = "Dakika",
                            WordIndex = 18
                        },
                        new
                        {
                            Id = 5,
                            DataType = "short",
                            ParameterKey = "DOSING_QUANTITY_LITERS",
                            StepTypeDefinitionId = 4,
                            Unit = "Litre",
                            WordIndex = 11
                        },
                        new
                        {
                            Id = 6,
                            DataType = "string(6)",
                            ParameterKey = "CHEMICAL_NAME",
                            StepTypeDefinitionId = 4,
                            Unit = "",
                            WordIndex = 21
                        },
                        new
                        {
                            Id = 7,
                            DataType = "short",
                            ParameterKey = "SPIN_DURATION_MINUTES",
                            StepTypeDefinitionId = 6,
                            Unit = "Dakika",
                            WordIndex = 9
                        });
                });

            modelBuilder.Entity("Universalscada.Core.Meta.StepTypeDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalculationServiceKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ControlWordBit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayNameKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UniversalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StepTypeDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CalculationServiceKey = "WaterTime",
                            ControlWordBit = 0,
                            DisplayNameKey = "Su Alma",
                            UniversalName = "WATER_TRANSFER"
                        },
                        new
                        {
                            Id = 2,
                            CalculationServiceKey = "HeatTime",
                            ControlWordBit = 1,
                            DisplayNameKey = "Isıtma",
                            UniversalName = "HEAT_RAMP"
                        },
                        new
                        {
                            Id = 3,
                            CalculationServiceKey = "SimpleTime",
                            ControlWordBit = 2,
                            DisplayNameKey = "Çalışma",
                            UniversalName = "MECHANICAL_WORK"
                        },
                        new
                        {
                            Id = 4,
                            CalculationServiceKey = "DosingTime",
                            ControlWordBit = 3,
                            DisplayNameKey = "Dozaj",
                            UniversalName = "DOSING_CHEMICAL"
                        },
                        new
                        {
                            Id = 5,
                            CalculationServiceKey = "ConstantTime",
                            ControlWordBit = 4,
                            DisplayNameKey = "Boşaltma",
                            UniversalName = "DRAIN"
                        },
                        new
                        {
                            Id = 6,
                            CalculationServiceKey = "SimpleTime",
                            ControlWordBit = 5,
                            DisplayNameKey = "Sıkma",
                            UniversalName = "SPIN_DRY"
                        });
                });

            modelBuilder.Entity("Universalscada.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FtpPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FtpUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineSubType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineUserDefinedId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VncAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VncPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("Universalscada.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Universalscada.Models.ScadaRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetMachineType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Universalscada.Models.ScadaRecipeStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ScadaRecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StepDataWords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StepNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScadaRecipeId");

                    b.ToTable("RecipeSteps");
                });

            modelBuilder.Entity("Universalscada.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Universalscada.Core.Meta.StepParameterDefinition", b =>
                {
                    b.HasOne("Universalscada.Core.Meta.StepTypeDefinition", "StepTypeDefinition")
                        .WithMany("Parameters")
                        .HasForeignKey("StepTypeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StepTypeDefinition");
                });

            modelBuilder.Entity("Universalscada.Models.Role", b =>
                {
                    b.HasOne("Universalscada.Models.User", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Universalscada.Models.ScadaRecipeStep", b =>
                {
                    b.HasOne("Universalscada.Models.ScadaRecipe", null)
                        .WithMany("Steps")
                        .HasForeignKey("ScadaRecipeId");
                });

            modelBuilder.Entity("Universalscada.Core.Meta.StepTypeDefinition", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Universalscada.Models.ScadaRecipe", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Universalscada.Models.User", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
