//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universalscada.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Universalscada.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Yetki Reddedildi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AccessDeniedTitle {
            get {
                return ResourceManager.GetString("AccessDeniedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aktif Üretim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ActiveProductionKpi {
            get {
                return ResourceManager.GetString("ActiveProductionKpi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alarm Numarası ve Alarm Metni zorunludur. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AlarmCodeTextRequiredMessage {
            get {
                return ResourceManager.GetString("AlarmCodeTextRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alarm Tanımlama benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AlarmDefinitionTitle {
            get {
                return ResourceManager.GetString("AlarmDefinitionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alarm Detayları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AlarmDetailsTitle {
            get {
                return ResourceManager.GetString("AlarmDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geçmiş Alarmlar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AlarmHistoryTitle {
            get {
                return ResourceManager.GetString("AlarmHistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alarm Metni: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AlarmMessageLabel {
            get {
                return ResourceManager.GetString("AlarmMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alarm No: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AlarmNumberLabel {
            get {
                return ResourceManager.GetString("AlarmNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alarm raporları oluşturulurken hata oluştu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AlarmReportGenerationErrorMessage {
            get {
                return ResourceManager.GetString("AlarmReportGenerationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geçmiş Alarmlar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AlarmReportTitle {
            get {
                return ResourceManager.GetString("AlarmReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alarm Durumu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AlarmStatusKpi {
            get {
                return ResourceManager.GetString("AlarmStatusKpi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alarm benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AlarmTitle {
            get {
                return ResourceManager.GetString("AlarmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Anali Et benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AnalyzeButton {
            get {
                return ResourceManager.GetString("AnalyzeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ortalama Çevrim Süresi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AverageCycleTimeTitle {
            get {
                return ResourceManager.GetString("AverageCycleTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ortalama Elektrik Tüketimi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AverageElectricityConsumptionTitle {
            get {
                return ResourceManager.GetString("AverageElectricityConsumptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ortalama Elektrik Tüketimi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AverageHourlyElectricityKpi {
            get {
                return ResourceManager.GetString("AverageHourlyElectricityKpi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ortalama Buhar Tüketimi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AverageSteamConsumptionTitle {
            get {
                return ResourceManager.GetString("AverageSteamConsumptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ortalama Su Tüketimi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AverageWaterConsumptionTitle {
            get {
                return ResourceManager.GetString("AverageWaterConsumptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt; GERİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Batch No: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BatchNoLabel {
            get {
                return ResourceManager.GetString("BatchNoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parti başlangıç zamanı bulunamadı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BatchStartTimeMissingMessage {
            get {
                return ResourceManager.GetString("BatchStartTimeMissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BY Makineleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ByMachineGroup {
            get {
                return ResourceManager.GetString("ByMachineGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İptal benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kategori: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CategoryLabel {
            get {
                return ResourceManager.GetString("CategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kimyasal Tüketimi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ChemicalConsumptionTitle {
            get {
                return ResourceManager.GetString("ChemicalConsumptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kimyasal: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ChemicalLabel {
            get {
                return ResourceManager.GetString("ChemicalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kimyasal Çözme Süresi: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ChemicalMixingTimeLabel {
            get {
                return ResourceManager.GetString("ChemicalMixingTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kapat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Program kapanırken VNCViewer formunu kapatma hatası: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CloseVNCErrorMessage {
            get {
                return ResourceManager.GetString("CloseVNCErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Soğuk Su benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ColdWaterLabel {
            get {
                return ResourceManager.GetString("ColdWaterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Karşılaştırılacak : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CompareWithLabel {
            get {
                return ResourceManager.GetString("CompareWithLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   alarm tanımını silmek istediğinizden emin misiniz? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ConfirmAlarmDefinitionDeleteMessage {
            get {
                return ResourceManager.GetString("ConfirmAlarmDefinitionDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Onay benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ConfirmationTitle {
            get {
                return ResourceManager.GetString("ConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silme Onayı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çıkış yapmak istediğinize emin misiniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ConfirmLogoutMessage {
            get {
                return ResourceManager.GetString("ConfirmLogoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   makinesini silmek istediğinizden emin misiniz? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ConfirmMachineDeleteMessage {
            get {
                return ResourceManager.GetString("ConfirmMachineDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   kullanıcısını silmek istediğinizden emin misiniz? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ConfirmUserDeleteMessage {
            get {
                return ResourceManager.GetString("ConfirmUserDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bağlantı Hatası benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ConnectionErrorTitle {
            get {
                return ResourceManager.GetString("ConnectionErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bağlantı Kesildi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ConnectionLostMessage {
            get {
                return ResourceManager.GetString("ConnectionLostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bağlantı bekleniyor... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ConnectionWaitingMessage {
            get {
                return ResourceManager.GetString("ConnectionWaitingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tüketim Tipi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ConsumptionTypeLabel {
            get {
                return ResourceManager.GetString("ConsumptionTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Soğutma Süresi (dk): benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CoolingTimeMinutesLabel {
            get {
                return ResourceManager.GetString("CoolingTimeMinutesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maliyet Parametreleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CostParametersTitle {
            get {
                return ResourceManager.GetString("CostParametersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kritik Hata benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CriticalErrorTitle {
            get {
                return ResourceManager.GetString("CriticalErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Müşteri No: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CustomerNoLabel {
            get {
                return ResourceManager.GetString("CustomerNoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Veritabanı bağlantısı kurulamadı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DatabaseConnectionFailedMessage {
            get {
                return ResourceManager.GetString("DatabaseConnectionFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Veritabanı Hatası benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DatabaseErrorTitle {
            get {
                return ResourceManager.GetString("DatabaseErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Görüntülenecek veriler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DataToDisplayLabel {
            get {
                return ResourceManager.GetString("DataToDisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tarih Aralığı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DateRangeLabel {
            get {
                return ResourceManager.GetString("DateRangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silme Onayı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeleteConfirmationTitle {
            get {
                return ResourceManager.GetString("DeleteConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silme sırasında hata: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeleteErrorMessage {
            get {
                return ResourceManager.GetString("DeleteErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Direk Buhar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DirectSteamLabel {
            get {
                return ResourceManager.GetString("DirectSteamLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dozaj benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DosageActionShort {
            get {
                return ResourceManager.GetString("DosageActionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dozajda Litre: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DosageLitersLabel {
            get {
                return ResourceManager.GetString("DosageLitersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOZAJ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DosageStepTitle {
            get {
                return ResourceManager.GetString("DosageStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kimyasal Dozaj Süresi: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DosageTimeLabel {
            get {
                return ResourceManager.GetString("DosageTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Boşaltma benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DrainActionShort {
            get {
                return ResourceManager.GetString("DrainActionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BOŞALTMA benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DrainStepTitle {
            get {
                return ResourceManager.GetString("DrainStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tambur Dur benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DrumStopAction {
            get {
                return ResourceManager.GetString("DrumStopAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kurutma Makinesi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DryingMachineGroup {
            get {
                return ResourceManager.GetString("DryingMachineGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kurutma Reçete Parametleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DryingRecipeParametersTitle {
            get {
                return ResourceManager.GetString("DryingRecipeParametersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Süre (dk): benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DurationMinutesLabel {
            get {
                return ResourceManager.GetString("DurationMinutesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Elektrik benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ElectricityShort {
            get {
                return ResourceManager.GetString("ElectricityShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bitiş Tarihi: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EndDateFullLabel {
            get {
                return ResourceManager.GetString("EndDateFullLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bitiş Tarihi: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EndDateLabel {
            get {
                return ResourceManager.GetString("EndDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İngilizce benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EnglishLanguageName {
            get {
                return ResourceManager.GetString("EnglishLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hata benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excel&apos;e Aktar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExportToExcelButton {
            get {
                return ResourceManager.GetString("ExportToExcelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FTP Şifre : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FtpPasswordLabel {
            get {
                return ResourceManager.GetString("FtpPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FTP Kullanıcı : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FtpUsernameLabel {
            get {
                return ResourceManager.GetString("FtpUsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Genel Tüketim Raporu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GeneralConsumptionReportTitle {
            get {
                return ResourceManager.GetString("GeneralConsumptionReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Genel Tesis Dashboard&apos;u (KPI Ekranı) (Burası Geliştirilecek) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GeneralFactoryDashboardTitle {
            get {
                return ResourceManager.GetString("GeneralFactoryDashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Genel Bakış benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GeneralOverviewTitle {
            get {
                return ResourceManager.GetString("GeneralOverviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grafiği Oluştur benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GenerateGraphButton {
            get {
                return ResourceManager.GetString("GenerateGraphButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rapor Oluştur benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GenerateReportButton {
            get {
                return ResourceManager.GetString("GenerateReportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Isıtma benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HeatingActionShort {
            get {
                return ResourceManager.GetString("HeatingActionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ISITMA benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HeatingStepTitle {
            get {
                return ResourceManager.GetString("HeatingStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sıcak Su benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HotWaterLabel {
            get {
                return ResourceManager.GetString("HotWaterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saatlik Elektirk Tüketimi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HourlyElectricityConsumptionChartTitle {
            get {
                return ResourceManager.GetString("HourlyElectricityConsumptionChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nem (%): benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HumidityPercentageLabel {
            get {
                return ResourceManager.GetString("HumidityPercentageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Boşta Bekleyen benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string IdleWaitingKpi {
            get {
                return ResourceManager.GetString("IdleWaitingKpi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dolaylı Buhar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string IndirectSteamLabel {
            get {
                return ResourceManager.GetString("IndirectSteamLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bilgi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string InformationTitle {
            get {
                return ResourceManager.GetString("InformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Giriş Gerekli benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string InputRequiredTitle {
            get {
                return ResourceManager.GetString("InputRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP Adresi : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string IpAddressLabel {
            get {
                return ResourceManager.GetString("IpAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LanguageMenu {
            get {
                return ResourceManager.GetString("LanguageMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Canlı veri akışı bekleniyor... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LiveDataWaitingMessage {
            get {
                return ResourceManager.GetString("LiveDataWaitingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Canlı Proses Verileri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LiveProcessDataTitle {
            get {
                return ResourceManager.GetString("LiveProcessDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Giriş Yapan benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LoggedInUserLabel {
            get {
                return ResourceManager.GetString("LoggedInUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Giriş Yap benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı adı veya şifre hatalı! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LoginFailedMessage {
            get {
                return ResourceManager.GetString("LoginFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SCADA Sistemi - Giriş benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LoginScreenTitle {
            get {
                return ResourceManager.GetString("LoginScreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Giriş/Çıkış benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LogoutButton {
            get {
                return ResourceManager.GetString("LogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Makine bağlantısı bulunamadı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MachineConnectionNotFoundMessage {
            get {
                return ResourceManager.GetString("MachineConnectionNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Makine Grubu : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MachineGroupLabel {
            get {
                return ResourceManager.GetString("MachineGroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Makine ID ve IP Adresi alanları zorunludur. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MachineIdIpRequiredMessage {
            get {
                return ResourceManager.GetString("MachineIdIpRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MAKİNA ID: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MachineIDLabel {
            get {
                return ResourceManager.GetString("MachineIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Makine Bilgileri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MachineInformationTitle {
            get {
                return ResourceManager.GetString("MachineInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Makine bilgileri başarıyla güncellendi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MachineInfoUpdateSuccessMessage {
            get {
                return ResourceManager.GetString("MachineInfoUpdateSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Makine: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MachineLabel {
            get {
                return ResourceManager.GetString("MachineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Makineler yüklenirken hata oluştu : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MachineLoadErrorMessage {
            get {
                return ResourceManager.GetString("MachineLoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Makine Yönetimi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MachineManagementTitle {
            get {
                return ResourceManager.GetString("MachineManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MAKİNA ADI: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MachineNameLabel {
            get {
                return ResourceManager.GetString("MachineNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Makineler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MachinesLabel {
            get {
                return ResourceManager.GetString("MachinesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Makine Tipi : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MachineTypeLabel {
            get {
                return ResourceManager.GetString("MachineTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ana Tank Temiz Su Al benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MainTankCleanWaterIntake {
            get {
                return ResourceManager.GetString("MainTankCleanWaterIntake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ana Tank Mak. Su Al benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MainTankWaterIntake {
            get {
                return ResourceManager.GetString("MainTankWaterIntake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manuel Tüketimler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ManualConsumptionReportTitle {
            get {
                return ResourceManager.GetString("ManualConsumptionReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ana Reçete: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MasterRecipeLabel {
            get {
                return ResourceManager.GetString("MasterRecipeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eksik Bilgi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MissingInformationTitle {
            get {
                return ResourceManager.GetString("MissingInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İzleme aktif mi ? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MonitoringActiveQuestion {
            get {
                return ResourceManager.GetString("MonitoringActiveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ad Soyad benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NameSurnameLabel {
            get {
                return ResourceManager.GetString("NameSurnameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeni benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NewButton {
            get {
                return ResourceManager.GetString("NewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeni makine başarıyla eklendi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NewMachineSuccessMessage {
            get {
                return ResourceManager.GetString("NewMachineSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YENİ REÇETE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NewRecipeButton {
            get {
                return ResourceManager.GetString("NewRecipeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeni kullanıcı için şifre zorunludur. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NewUserPasswordRequiredMessage {
            get {
                return ResourceManager.GetString("NewUserPasswordRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bu alana erişim yetkiniz bulunmamaktadır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NoAccessMessage {
            get {
                return ResourceManager.GetString("NoAccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aktif alarm yok . benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NoActiveAlarmMessage {
            get {
                return ResourceManager.GetString("NoActiveAlarmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bu parti için kayıtlı alarm yok. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NoAlarmsForBatchMessage {
            get {
                return ResourceManager.GetString("NoAlarmsForBatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bu parti için henüz proses verisi kaydedilmemiş. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NoProcessDataForBatchMessage {
            get {
                return ResourceManager.GetString("NoProcessDataForBatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OEE Raporu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string OeeReportTitle {
            get {
                return ResourceManager.GetString("OeeReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tamam benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OPERATOR: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string OperatorLabel {
            get {
                return ResourceManager.GetString("OperatorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sipariş No: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string OrderNoLabel {
            get {
                return ResourceManager.GetString("OrderNoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diğer benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string OtherMachineType {
            get {
                return ResourceManager.GetString("OtherMachineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifre: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geçmiş Üretimler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PastProductionsTitle {
            get {
                return ResourceManager.GetString("PastProductionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PLC Operatör Yönetimi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PlcOperatorManagementTitle {
            get {
                return ResourceManager.GetString("PlcOperatorManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen işlem yapılacak makineyi seçin: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PleaseSelectMachineMessage {
            get {
                return ResourceManager.GetString("PleaseSelectMachineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Proses Alarmları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProcessAlarmsTitle {
            get {
                return ResourceManager.GetString("ProcessAlarmsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Proses Kontrol benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProcessControlTitle {
            get {
                return ResourceManager.GetString("ProcessControlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Proses Grafiği benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProcessGraphTitle {
            get {
                return ResourceManager.GetString("ProcessGraphTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PROSESSING benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProcessingTitle {
            get {
                return ResourceManager.GetString("ProcessingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Proses İzleme benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProcessMonitoringTitle {
            get {
                return ResourceManager.GetString("ProcessMonitoringTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Proses Zaman Çizgisi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProcessTimelineTitle {
            get {
                return ResourceManager.GetString("ProcessTimelineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Üretim Raporu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProductionReportTitle {
            get {
                return ResourceManager.GetString("ProductionReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Üretim Raporu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProductionReportTitleDuplicate {
            get {
                return ResourceManager.GetString("ProductionReportTitleDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Üretim Özeti benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProductionSummaryTitle {
            get {
                return ResourceManager.GetString("ProductionSummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Miktar (Litre): benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string QuantityLitersLabel {
            get {
                return ResourceManager.GetString("QuantityLitersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reçete PLC&apos;den okunuyor... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ReadingRecipeFromPlcMessage {
            get {
                return ResourceManager.GetString("ReadingRecipeFromPlcMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RECETE ADI: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RecipeNameLabel {
            get {
                return ResourceManager.GetString("RecipeNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reçete Optimizasyon benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RecipeOptimizationTitle {
            get {
                return ResourceManager.GetString("RecipeOptimizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PLC&apos;den reçete okunamadı: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RecipeReadPlcErrorMessage {
            get {
                return ResourceManager.GetString("RecipeReadPlcErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reçete Adım Tasaramı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RecipeStepDesignerTitle {
            get {
                return ResourceManager.GetString("RecipeStepDesignerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rapor oluşturulurken bir hata oluştu: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ReportGenerationErrorMessage {
            get {
                return ResourceManager.GetString("ReportGenerationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Raporlar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ReportsMenuTitle {
            get {
                return ResourceManager.GetString("ReportsMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sağ-Sol Yön Süre (SN): benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RightLeftTimeSecondsLabel {
            get {
                return ResourceManager.GetString("RightLeftTimeSecondsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Roller benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RolesLabel {
            get {
                return ResourceManager.GetString("RolesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Devir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RpmLabel {
            get {
                return ResourceManager.GetString("RpmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çalışma benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RunningActionShort {
            get {
                return ResourceManager.GetString("RunningActionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çalışma Süresi (DK): benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RunningDurationMinutesLabel {
            get {
                return ResourceManager.GetString("RunningDurationMinutesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çalışma Devri: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RunningSpeedLabel {
            get {
                return ResourceManager.GetString("RunningSpeedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÇALIŞMA benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RunningStepTitle {
            get {
                return ResourceManager.GetString("RunningStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kaydet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kayıt sırasında bir hata oluştu: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SaveErrorGeneralMessage {
            get {
                return ResourceManager.GetString("SaveErrorGeneralMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kayıt sırasında hata: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SaveErrorMessage {
            get {
                return ResourceManager.GetString("SaveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tekstil SCADA Sistemi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ScadaSystemTitle {
            get {
                return ResourceManager.GetString("ScadaSystemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen silmek için bir alarm tanımı seçin. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SelectAlarmToDeleteMessage {
            get {
                return ResourceManager.GetString("SelectAlarmToDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen en az bir makine seçin. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SelectAtLeastOneMachineMessage {
            get {
                return ResourceManager.GetString("SelectAtLeastOneMachineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Makine Seç benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SelectMachineButton {
            get {
                return ResourceManager.GetString("SelectMachineButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen silmek için bir makine seçin. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SelectMachineToDeleteMessage {
            get {
                return ResourceManager.GetString("SelectMachineToDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oturum benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SessionTitle {
            get {
                return ResourceManager.GetString("SessionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ayarlar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Önem Derecesi: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SeverityLabel {
            get {
                return ResourceManager.GetString("SeverityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yumuşak Su benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SoftWaterLabel {
            get {
                return ResourceManager.GetString("SoftWaterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sıkma benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SqueezingActionShort {
            get {
                return ResourceManager.GetString("SqueezingActionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sıkma Süre (DK): benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SqueezingDurationMinutesLabel {
            get {
                return ResourceManager.GetString("SqueezingDurationMinutesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sıkma Devri: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SqueezingSpeedLabel {
            get {
                return ResourceManager.GetString("SqueezingSpeedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SIKMA benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SqueezingStepTitle {
            get {
                return ResourceManager.GetString("SqueezingStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başlangıç Tarihi: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string StartDateFullLabel {
            get {
                return ResourceManager.GetString("StartDateFullLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başlangıç Tarihi: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string StartDateLabel {
            get {
                return ResourceManager.GetString("StartDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Buhar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SteamShort {
            get {
                return ResourceManager.GetString("SteamShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adım Detayları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string StepDetailsTitle {
            get {
                return ResourceManager.GetString("StepDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ADIM: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string StepLabel {
            get {
                return ResourceManager.GetString("StepLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1. Tank Dozaj benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Tank1DosageLabel {
            get {
                return ResourceManager.GetString("Tank1DosageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1. Tank Su Al benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Tank1WaterIntake {
            get {
                return ResourceManager.GetString("Tank1WaterIntake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tank Alınan Su: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TankWaterAmountLabel {
            get {
                return ResourceManager.GetString("TankWaterAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Isı (°C): benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TemperatureCelsiusLabel {
            get {
                return ResourceManager.GetString("TemperatureCelsiusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Isı Kontrol benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TemperatureControlTitle {
            get {
                return ResourceManager.GetString("TemperatureControlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   En Sık 5 Alarm (Son 24 Saat) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Top5AlarmsKpi {
            get {
                return ResourceManager.GetString("Top5AlarmsKpi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Son 24 Saatin Popüler Alarmları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TopAlarmsLast24HoursTitle {
            get {
                return ResourceManager.GetString("TopAlarmsLast24HoursTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tüm Makineler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TotalMachinesCountLabel {
            get {
                return ResourceManager.GetString("TotalMachinesCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toplam Süre: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TotalTimeLabel {
            get {
                return ResourceManager.GetString("TotalTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trend Analiz Raporu (Geliştirilecek) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TrendAnalysisReportTitle {
            get {
                return ResourceManager.GetString("TrendAnalysisReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trend Analizi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TrendAnalysisTitle {
            get {
                return ResourceManager.GetString("TrendAnalysisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Türkçe benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TurkishLanguageName {
            get {
                return ResourceManager.GetString("TurkishLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı Aktif benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UserActiveLabel {
            get {
                return ResourceManager.GetString("UserActiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı Detayları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UserDetailTitle {
            get {
                return ResourceManager.GetString("UserDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı Yönetimi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UserManagementTitle {
            get {
                return ResourceManager.GetString("UserManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı Adı: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı adı zorunludur. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UsernameRequiredMessage {
            get {
                return ResourceManager.GetString("UsernameRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Canlı Olay Akışı Göster benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ViewLiveEventStreamButton {
            get {
                return ResourceManager.GetString("ViewLiveEventStreamButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VNC Adresi : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string VncAddressLabel {
            get {
                return ResourceManager.GetString("VncAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zaten bir VNC bağlantısı aktif. Lütfen mevcut pencereyi kapatın. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string VncAlreadyOpenMessage {
            get {
                return ResourceManager.GetString("VncAlreadyOpenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VNC penceresi açılırken bir hata oluştu: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string VncConnectErrorMessage {
            get {
                return ResourceManager.GetString("VncConnectErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VNC Bağlantısı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string VncConnectionTitle {
            get {
                return ResourceManager.GetString("VncConnectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bu makine için bir VNC adresi tanımlanmamış. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string VncNoAddressMessage {
            get {
                return ResourceManager.GetString("VncNoAddressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bekleme Süresi (SN): benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string WaitTimeSecondsLabel {
            get {
                return ResourceManager.GetString("WaitTimeSecondsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uyarı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Su Alma benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string WaterIntakeActionShort {
            get {
                return ResourceManager.GetString("WaterIntakeActionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SU ALMA benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string WaterIntakeStepTitle {
            get {
                return ResourceManager.GetString("WaterIntakeStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Su seviyesi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string WaterLevelLabel {
            get {
                return ResourceManager.GetString("WaterLevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Su benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string WaterShort {
            get {
                return ResourceManager.GetString("WaterShort", resourceCulture);
            }
        }
    }
}
